package com.delivery.sopo.enums

enum class ResponseCode(val CODE: String, val MSG: String) {
    SUCCESS("0000", "SUCCESS"),
    VALIDATION_ERROR("VA01",""),
    KAKAO_SIMPLE_FAIL("KA00", "Fail to join by kakao"),
    KAKAO_SIMPLE_ALREADY_USE_EMAIL("KA01", "Already use that email"),
    KAKAO_SIMPLE_NOT_VERIFYED_USER("KA02", "Can not verify kakao user"),
    KAKAO_SIMPLE_CORRUPT_EMAIL("KA03", "Corrupted Email"),
    KAKAO_SIMPLE_FAIL_TO_PASING_DATA("KA04", "Fail to parse the kakao data"),
    KAKAO_SIMPLE_CORRUPT_EMAIL2("KA05", "After verify kakao user, doesn`t match email(parameter != user data)"),
    KAKAO_SIMPLE_CANNOT_FIND_FIREBASE_USER("KA06", "Can not find firebase user searched by email"),
    FAIL_TO_FIND_API_ACCOUNT("AP01","Can`t find api account!"),
    FAIL_TO_FIND_SOPO_USER("AP02", "Can`t find Sopo User"),
    FAIL_TO_SAVE_API_ACCOUNT("AP03", "Fail to save Api account"),
    FAIL_TO_SAVE_SOPO_USER("AP04", "Fail to save Sopo User"),
    NOT_VALID_USER("AP05", "Not valid user"),
    FAIL_TO_REQUEST_FOR_UPDATING("UP01", "Fail to request for updating"),
    SEARCH_PARCEL_NULL_ERROR("PC01", "DeliveryTracking api`s result is null"),
    FAIL_TO_SAVE_PARCEL("PC02","fail to save client`s parcel"),
    FAIL_TO_SEARCH_PARCEL("PC03","fail to get client`s parcel [Delivery Api]"),
    CAN_NOT_FIND_PARCEL("PC04","Can`t find a parcel"),
    FAIL_TO_FIND_PARCEL("PC05","Fail to find a parcel"),
    FAIL_TO_UPDATE_USER_FIREBASE_TOKEN("US01","Fail to update user`s firebase token"),
    UNKNOWN_ERROR("9999", "UNKNOWN_ERROR"),
    UNAUTHORIZED_ACCESS_ERROR("BC01", "UNAUTHORIZED ACCESS"),
    NOT_FOUND_ERROR("BC02", "NOT FOUND"),
    FORBIDDEN_ACCESS_ERROR("BC03", "FORBIDDEN ACCESS"),
    JWT_INVALID_SIGNATURE("JW01", "Invalid JWT signature"),
    JWT_INVALID("JW99", "Invalid JWT token"),
    JWT_EXPIRED_TOKEN("JW02", "Expired JWT token"),
    JWT_UNSUPPORTED_TOKEN("JW03","Unsupported JWT token"),
    JWT_ILLEGALARGUMENT("JW04","JWT claims string is empty")
}